"""initial schema

Revision ID: b67602a8a60f
Revises: 
Create Date: 2026-05-26 16:58:32.417185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b67602a8a60f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('hashed_pw', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('applied', 'interviewing', 'offer', 'rejected', name='application_status'), server_default=sa.text("'applied'"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('salary_range', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_applications_applied_at', 'applications', ['user_id', sa.text('applied_at DESC')], unique=False)
    op.create_index('idx_applications_user_id', 'applications', ['user_id'], unique=False)
    op.create_index('idx_applications_user_status', 'applications', ['user_id', 'status'], unique=False)
    op.create_table('cv_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_cv_profiles_updated_at', 'cv_profiles', ['updated_at'], unique=False)
    op.create_index('idx_cv_profiles_user_id', 'cv_profiles', ['user_id'], unique=True)
    op.create_table('cv_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('r2_key', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'embedding', 'done', 'error', name='cv_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cv_versions_user_id', 'cv_versions', ['user_id'], unique=False)
    op.create_index('idx_cv_versions_user_status', 'cv_versions', ['user_id', 'status'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_goals_user_completed', 'goals', ['user_id', 'completed_at'], unique=False)
    op.create_index('idx_goals_user_id', 'goals', ['user_id'], unique=False)
    op.create_table('nudges',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_nudges_user_id', 'nudges', ['user_id'], unique=False)
    op.create_index('idx_nudges_user_unread', 'nudges', ['user_id', 'read'], unique=False, postgresql_where=sa.text('read = FALSE'))
    op.create_table('calendar_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('start_dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('end_dt > start_dt', name='chk_end_after_start'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calendar_events_range', 'calendar_events', ['user_id', 'start_dt', 'end_dt'], unique=False)
    op.create_index('idx_calendar_events_user_id', 'calendar_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_calendar_events_user_id', table_name='calendar_events')
    op.drop_index('idx_calendar_events_range', table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index('idx_nudges_user_unread', table_name='nudges', postgresql_where=sa.text('read = FALSE'))
    op.drop_index('idx_nudges_user_id', table_name='nudges')
    op.drop_table('nudges')
    op.drop_index('idx_goals_user_id', table_name='goals')
    op.drop_index('idx_goals_user_completed', table_name='goals')
    op.drop_table('goals')
    op.drop_index('idx_cv_versions_user_status', table_name='cv_versions')
    op.drop_index('idx_cv_versions_user_id', table_name='cv_versions')
    op.drop_table('cv_versions')
    op.drop_index('idx_cv_profiles_user_id', table_name='cv_profiles')
    op.drop_index('idx_cv_profiles_updated_at', table_name='cv_profiles')
    op.drop_table('cv_profiles')
    op.drop_index('idx_applications_user_status', table_name='applications')
    op.drop_index('idx_applications_user_id', table_name='applications')
    op.drop_index('idx_applications_applied_at', table_name='applications')
    op.drop_table('applications')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
